# Unique list of necessary libraries

library(aoh)
library(terra)
library(sf)
library(stars)
#library(rappdirs)
#library(ggplot2)
#library(ggmap)
library(tidyverse)
library(janitor)
library(dplyr)
#library(profvis)
#library(pryr)
#library(tictoc)
library(stringr)
library(data.table)
#library(parallel)
# for the validation protocol
library(insight)
library(lme4)
library(glmmTMB)
library(rlist)


library(foreach) 
library(cluster)
#library(doParallel)
library(doSNOW)

# library(aoh)
# library(terra)
# library(rappdirs)
# library(ggplot2)
# library(ggmap)
# library(tidyverse)
# library(janitor)
# library(dplyr)
# library(zen4R)
# library(profvis)
# library(pryr)
# library(rgrass7)
# library(tictoc)
# library(tidyverse)
# library(stringr)