#### lookup paths #####
type=str_remove(type, "\\/")
type = paste0(type, "_", projection, "/")
model_prev_loc <- normalizePath(paste0("../aoh_out/output_R/", class, "/", type)) #, "area/")
ras_loc <- normalizePath(paste0("../aoh_out/output_R/", class, "/", type))
### set output directories######
out_dir <- "../aoh_out/output_R/validation/point_prevalence/"
out_class <- paste0(out_dir, class, "/", type)
out_tmp_rast <- paste0(out_class, "/tmp_rasters_points_", type)
out_tmp_csv <- paste0(out_class, "/tmp_csv_", type)
out_tmp_buffered <- paste0(out_class, "/tmp_rasters_buffer_", type)
out_tmp_shp <- paste0(out_class, "/tmp_shp_", type)
if(!dir.exists("../aoh_out/output_R/validation/")) dir.create("../aoh_out/output_R/validation/")
if(!dir.exists(out_dir)) dir.create(out_dir)
if(!dir.exists(paste0(out_dir, class, "/"))) dir.create(paste0(out_dir, class, "/"))
if(!dir.exists(out_class)) dir.create(out_class)
if(!dir.exists(out_tmp_rast)) dir.create(out_tmp_rast)
if(!dir.exists(out_tmp_shp)) dir.create(out_tmp_shp)
if(!dir.exists(out_tmp_csv)) dir.create(out_tmp_csv)
if(!dir.exists(out_tmp_buffered)) dir.create(out_tmp_buffered)
shp_dir = paste0(out_tmp_rast, "shp")
if(!dir.exists(shp_dir)) dir.create(shp_dir)
shp_dir = normalizePath(shp_dir)
out_dir = normalizePath(out_dir)
out_class = normalizePath(out_class)
out_tmp_rast = normalizePath(out_tmp_rast)
out_tmp_buffered = normalizePath(out_tmp_buffered)
out_tmp_shp = normalizePath(out_tmp_shp)
source("rscripts/aoh_jeff_4wcmc/src_files/calculate_area.R")
